[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.ruff]
line-length = 120
target-version = "py310"

[tool.ruff.lint]
extend-select = ["ANN", "ASYNC", "I", "UP"]
ignore = ["ANN101", "ANN102", "ANN401","D100"]